title: The DBA Chronicles
email: your-email@example.com
description: >-
  Real-world Oracle & PostgreSQL notes from İbrahim Güler.
baseurl: "/dba-blog"
url: "https://dba-iguler.github.io"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
paginate: 5
paginate_path: "/page:num/"
author:
  name: İbrahim Güler
  avatar: "/assets/images/avatar.png"
  bio: "Senior DBA | Oracle & PostgreSQL"
